### ISSUE TITLE
Make it look nice

### ISSUE THREAD

**Issue by khalillechelt** [cilice/fido-web#1]
Basic functionality seems to be there if I understand @cilice, so now we just have to give it a simple clean look to launch an Alpha on a free heroku account. @ollicle did you want to maybe look into this?

**Comment by ollicle** [comment]
Sure, although I can’t make any promises on timeliness. So all other efforts are welcome :)

Looking nice requires a good structure, so as a start I spent some time thinking about the HTML: http://output.jsbin.com/rukepe

The basic thought is that the query is expressed as a single phrase with form elements inserted at appropriate points in the sentence. In one line we get the interface and immediate purpose of the app.

Included is http://leaverou.github.io/stretchy/ to minimises the width of the form elements – making them behave more like words.

Also added some additional details to the reviews themselves.

**Comment by ollicle** [comment]
With some basic styling: http://output.jsbin.com/qozece/3

**Comment by ollicle** [comment]
Played some more today: http://output.jsbin.com/qozece/10
That round button is supposed to be a ball – think of it as a rough CSS sketch.

**Comment by khalillechelt** [comment]
Great start! Thanks Ollie!

Von meinem iPhone gesendet

**Comment by cilice** [comment]
Could you help me out, which components should I pick there? http://www.material-ui.com/#/components/appbar

Otherwise I'd just go without material design, as I'm not a big fan of it.

**Comment by cilice** [comment]
And I started deploying it on http://fido.surge.sh/

**Comment by khalillechelt** [comment]
@cilice No need to use material design since we already have a rudimentary UI thanks to @ollicle (see above). Can you use that? I'd like to iterate the design in the details a little later on but for starters its fine I'd say.

**Comment by cilice** [comment]
Sure, could do :)

**Comment by cilice** [comment]
@ollicle We need a simple way to add podcasts, selecting one in the dropdown has no way to add or delete one from the dropdown.

**Comment by ollicle** [comment]
@cilice Indeed, would be nice to have a welcome with a somewhat different view for adding your first podcast. Does a separate view fall within simple?

**Comment by khalillechelt** [comment]
I am closing this ticket. Enhancements on the UI should be discussed in their own respective tickets. 
The improvement for adding podcasts is being addressed in #4.
